### ISSUE TITLE
Works with the BGI V2 version?

### ISSUE THREAD

**Issue by Aleisster** [xmoeproject/BGITool#1]
The tools works with games like Aokana, Tayutama 2, Magical charming or such? If is so, how should I pack the .txt again?

**Comment by 0xh3LL0** [comment]
i believe bgi v2 use the same format as v1, so the tools should be working.
unless you want to translate old games like mangagamer's da capo release, which use very old bgi (v0.XX, probably?)

**Comment by Aleisster** [comment]
It seems just work for extracting the dataxxx.arc, but there's no tool (or maybe support) for script unpack, repack of BGI v2

**Comment by xmoezzz** [comment]
Yep, this tool works with BGI newer version, but maybe fail to decode image
file.

2017年12月13日(水) 3:03 Senri <notifications@github.com>:
